# myApp/docker-compose.yaml

services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
  mongodb:
    image: mongo
    container_name: mongodb_c
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
# Add named volume for MongoDB persistence
volumes:
  mongo-data: